@host = http://localhost:3000/api
@accesToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJpYXQiOjE3MDA3MDI1MTQsImV4cCI6MTcwMDc0NTcxNH0.lS2OGDw1HwBsKFjsOrXSzJWvVYuJv-nKGsKhuFxrjKE

### 내 정보 조회
GET {{host}}/user/profile
Authorization: Bearer {{accesToken}}


