@host = http://localhost:3000/api
@accesToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMDc2NjMwNCwiZXhwIjoxNzAwNzY2MzA1fQ.R2FFh6GCLNmJ36Gk3WnXXsmSh1NfJoyQxBLcqBNKfB0
### 내 정보 조회
GET {{host}}/user/me
Authorization: Bearer {{accesToken}}


